Django-project/first_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import include
from firstapp import urls as app_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(app_urls, namespace='firstapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django-project/firstapp/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView
app_name = 'firstapp'

urlpatterns = [
    path('',HomePageView.as_view(),name="index"), 
    path('detail/<int:pk>/',PostDetailView.as_view(),name='detail'),
    path('post/', AddPostView.as_view() ,name='post'),
]










Django-project/firstapp/models.py
from django.db import models
from sorl.thumbnail import ImageField
# Create your models here.
class post(models.Model):
    image = ImageField()
    text = models.CharField(max_length=140, blank=False, null=False)
    def __str__(self):
        return self.text

#class PostDetailView(models.Model):
    







Django-project/firstapp/forms.py
from django import forms

class PostForm(forms.Form):
    image = forms.ImageField()
    text = forms.CharField(label="Description")
    

Django-project/firstapp/views.py
#from django.shortcuts import render

# Create your views here.
from typing import Any
from django import http
from django.views.generic import TemplateView, DetailView, FormView
from .models import post
from .forms import PostForm
from django.contrib import messages

class HomePageView(TemplateView):
    
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_thing'] = "this is dynamic hi hello and welcome to my Page."
        context['posts'] = post.objects.all().order_by('-id')
        return context
    
class PostDetailView(DetailView):
    template_name = "detail.html"
    model = post

class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self,form):
        #  print(form.cleaned_data['text'])
        #  print(form.cleaned_data['image'])
        new_object = post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

    




Django-project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %}{%endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    {% if messages %}
        
        {% for message in messages %}
            <div class = "bg-{% if message.tags %}{{message.tags }}{% else %}success{% endif %}
                bg-gradient text-center text-white py-4">
               {{ message }}
            </div>
        {% endfor %}
       
    {% endif %}
    {% include "includes/navbar.html" %}

    <div class="container">
        {% block body %}{% endblock %}
    </div>

</body>
</html>

Django-project/templates/detail.html
{% extends "base.html" %}
{% block title %}
    This is Details views
{% endblock title %}
    
{% block body %}
    <div class="col-sm-10 offset-sm-1 py-5">
        <h3> {{object.text}} </h3>
        <img src="{{object.image.url}}" class="img-fluid rounded">
    </div>
{% endblock %}




Django-project/templates/home.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} HOME PAGE {% endblock %}

{% block body %}
   
    <div class="row">
        {% for post in posts %}
            <div class="col-sm-6 col-md-4">
                <div class="card" >
                    {% thumbnail post.image '100x100' crop="center" as im%}
                        <img src="{{im.url}}" class="card-img-top" alt="...">
                    {% endthumbnail %}
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{% url 'firstapp:detail' post.id %}" class="btn btn-primary">View Image</a>
                    </div>
                </div>
            </div>
            
            {% empty %}
                <div class="col-sm-6 offset-3 text-center py-5 my-5">
                    <h3>Welcome!</h3>
                    <p>Add your first image?</p>
                    <a href="{% url 'firstapp:post' %}" class="btn btn-lg btn-success"> Upload Image</a>
        {% endfor %}
    </div>
    
{% endblock %}






Django-project/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Image Sharer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href={% url 'firstapp:index' %}>Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href={% url 'firstapp:post' %}>Add New Image</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/admin/">Admin Page</a>
            </li>
            
        </ul>
        </div>
    </div>
</nav>

Django-project/templates/new_post.html
{% extends "base.html" %}

{% block title %}
    ADD_image and POST
{% endblock title %}

{% block body %}
    
    <form method="POST" action="" enctype="multipart/form-data" class="col-smj-4 offset-4">
        <h2>Upload Image</h2>
        {% csrf_token %}
        {{form.as_ul}}
        <div>
            <button type="submit"  class="btn btn-success" >Submit form
        </div>
{% endblock body %}